### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by auwtch** [CloneDeath/vox-importer#6]
I installed this add-on and added .vox file to project, but it's invisible in Files System panel

**Comment by CloneDeath** [comment]
Since you closed the issue, I imagine you resolved it.

Correct me if I'm wrong (and this is for future users who stumble across this ticket): I believe you likely forgot to enable to plugin in the settings menu. I do that all the time, and think something must be broken.

I wish Godot would enable installed plugins from the assets tab... I mean.. you did just choose to download and install it... why wouldn't you want to enable it? That should definitely be the default behavior IMO.

**Comment by auwtch** [comment]
Yes, this is the first plugin I installed, so I just did not know about plugin activation 😕
