### ISSUE TITLE
Plugin doesn't show in 3.1 addons folder

### ISSUE THREAD

**Issue by TomWor** [CloneDeath/vox-importer#7]
Hi, I activated the plugin in the project settings, just as been the case in another issue that was closed earlier here, but still the plugin seems not to be found by Godot. Am I missing something?
Is there a menu entry somewhere that could confirm it's activation?
And why wouldn't it show in the file explorer?

**Comment by TomWor** [comment]
I got it to work, and I just found out about the .gdignore file, which keeps Godot from parsing this directory.

**Comment by CloneDeath** [comment]
Yup. That was intentional. You don't need to access any files in there (additionally, all files for the plugin are self-contained in there), so I added the .gdignore for the user, so it doesn't unnecessarily clutter their project files in godot.

Any configuration you may want to do is in the import tab, so there really is no reason to poke around in there.

Lastly, if you do want them to show up (for whatever reason, maybe you're working on a PR to improve the plugin), you can simply uncheck (or delete) the .gdignore

(Just wanted to give some context onto why I did this, in case someone else stumbles upon this ticket)

**Comment by TomWor** [comment]
Thank you for the clarification!
I was a bit confused that the .gdignore means the files get ignored by the editor for inclusion in the filetree yet they DO get parsed for the addons functionality.
But all is good now, thanks.
